-- Last updated: 8/20/2026, 6:24:34 PM
# Write your MySQL query statement below
SELECT NAME AS CUSTOMERS
FROM CUSTOMERS
LEFT JOIN ORDERS
ON CUSTOMERS.ID=ORDERS.CUSTOMERID
WHERE ORDERS.CUSTOMERID IS NULL;